FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder

WORKDIR /go/src/github.com/openshift/cluster-resource-override-admission
COPY . .
RUN make build

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9

LABEL io.k8s.display-name="OpenShift ClusterResourceOverride Admission Webhook" \
      io.k8s.description="Manages level of overcommit of Pod Resource(s)" \
      io.openshift.tags="openshift,clusterresourceoverride"
COPY --from=builder /go/src/github.com/openshift/cluster-resource-override-admission/bin/cluster-resource-override-admission /usr/bin/
